### PR TITLE
GPUs issue fix?

### PR DESCRIPTION
**Pull request by vatai**
Fix - one liner attempt (issue #48)

### CODE REVIEW

**Comment by undertherain** [comment]
hm something strange is happening
```[0]blackbird@sugi:benchmarker$  [gpus-issue-gh48|✔]$ python3 -m unittest --verbose
test_res10ssd (test.opencv.test_res10ssd.OpenCvRes10SsdTest) ... ok
test_bert (test.pytorch.test_bert.PytorchBertTest) ... ok
test_cnn2d_inference (test.pytorch.test_cnn.PytorchCNNTest) ... ok
test_cnn2d_training (test.pytorch.test_cnn.PytorchCNNTest) ... ok
test_conv1d (test.pytorch.test_conv123d.PytorchConv123dTests) ... ok
test_conv2d (test.pytorch.test_conv123d.PytorchConv123dTests) ... ok
test_conv3d (test.pytorch.test_conv123d.PytorchConv123dTests) ... ok
test_lstm (test.pytorch.test_lstm.PytorchLstmTest) ... ok
test_resnet50 (test.pytorch.test_resnet50.PytorchResnet50Test) ... ok
test_resnet50_inference (test.pytorch.test_resnet50.PytorchResnet50Test) ... ok
test_ssd300 (test.pytorch.test_ssd300.PytorchSsd300Tests) ... ok
test_vgg16 (test.pytorch.test_vgg16.PytorchVgg16Test) ... ok
test_vgg16_inference (test.pytorch.test_vgg16.PytorchVgg16Test) ... ok
test_conv1d (test.tensorflow.test_conv123d.TensorflowConv123dTests) ... ok
test_conv2d (test.tensorflow.test_conv123d.TensorflowConv123dTests) ... ok
test_conv3d (test.tensorflow.test_conv123d.TensorflowConv123dTests) ... ok
test_resnet50 (test.tensorflow.test_resnet50.Resnet50Tests) ... ERROR
test_vgg16 (test.tensorflow.test_vgg16.TensorflowTests) ... 2020-06-16 06:17:00.871366: F tensorflow/core/common_runtime/gpu/gpu_util.cc:340] CPU->GPU Memcpy failed
Aborted (core dumped)
```

**Comment by undertherain** [comment]
anyways, that's because somehow it does not release memory after each test
the main point - it still runs on GPU

**Comment by undertherain** [comment]
```[0]blackbird@sugi:benchmarker$  [gpus-issue-gh48|✔]$ python3 -m benchmarker --framework=tensorflow --problem=vgg16 --problem_size=16 --batch_size=8
2020-06-16 06:22:16.008357: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-06-16 06:22:16.018554: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-16 06:22:16.018889: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:07:00.0 name: GeForce GTX 1060 6GB computeCapability: 6.1
coreClock: 1.7085GHz coreCount: 10 deviceMemorySize: 5.92GiB deviceMemoryBandwidth: 178.99GiB/s
2020-06-16 06:22:16.019078: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
``` etc

**Comment by vatai** [comment]
:thinking: Ok. I think I've got it. Probably like [this](https://www.tensorflow.org/guide/gpu#manual_device_placement).

**Comment by undertherain** [comment]
Hm but it was working before with CUDA_VISIBLE_DEVICES

Maybe new version of tf change behavior or that strategy thing :-/

**Comment by vatai** [comment]
Yes. Pushed one more commit. If this works I think the first commit can be reverted.

**Comment by vatai** [comment]
I think [this guy (or girl)](https://stackoverflow.com/a/53539790/568735) figured it out... you need to set it to -1. :thinking:

**Pull request merged**
