### PR TITLE
Gpus issue gh48

### PR DESCRIPTION
**Pull request by vatai**
I hope the logic is taken care of properly.

If you have `tensorflow-cpu` installed and run with `--gpus=0,1` it will say:
```
  File "/home/vatai/code/benchmarker/benchmarker/modules/do_tensorflow.py", line 27, in get_strategy
    assert gpu_count_same, "Tensorflow not compiled with GPU support"
```

Also fixed the `CUDA_VISIBLE_DEVICES` stuff a little. So apperently you should set it to the ids of the GPUs (basically the same as the value of our `--gpus`) or -1 if you want no GPUs.

### CODE REVIEW

**Comment by undertherain** [comment]
did you try to run on >1 gpus? any speedup?

**Comment by vatai** [comment]
Yes! Double speedup (if the problem and batch size is larger).

**Comment by undertherain** [comment]
Oh we should make batch per device to be a default command line option
But can merge this any time
Or I'll be back in 40m

**Comment by vatai** [comment]
Added another commit removing some code (some checks) which would never be reached (I think)... please take a look!

**Pull request merged**
